config/routes.rb
Rails.application.routes.draw do
 
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :emails

  mount Ckeditor::Engine => '/ckeditor'
 
  resources :apis

  resources :notifications

  resources :devices

  devise_for :admins, :skip=> 'registrations'
  root 'home#index'
  authenticate :admin do
  	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
    resources :contacts
  

end

app/models/api.rb
class Api < ActiveRecord::Base
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_api, only: [:show, :edit, :update, :destroy]

  # GET /apis
  # GET /apis.json
  def index
    @apis = Api.all
  end

  # GET /apis/1
  # GET /apis/1.json
  def show
  end

  # GET /apis/new
  def new
    @api = Api.new
  end

  # GET /apis/1/edit
  def edit
  end

  # POST /apis
  # POST /apis.json
  def create
    @api = Api.new(api_params)

    respond_to do |format|
      if @api.save
        format.html { redirect_to @api, notice: 'Api was successfully created.' }
        format.json { render :show, status: :created, location: @api }
      else
        format.html { render :new }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apis/1
  # PATCH/PUT /apis/1.json
  def update
    respond_to do |format|
      if @api.update(api_params)
        format.html { redirect_to @api, notice: 'Api was successfully updated.' }
        format.json { render :show, status: :ok, location: @api }
      else
        format.html { render :edit }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apis/1
  # DELETE /apis/1.json
  def destroy
    @api.destroy
    respond_to do |format|
      format.html { redirect_to apis_url, notice: 'Api was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api
      @api = Api.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def api_params
      params.require(:api).permit(:api_key)
    end
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/views/apis/_form.html.erb
<%= form_for @api, :html => { :class => "form-horizontal api" } do |f| %>

    <% if @api.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@api.errors.count, "error") %> prohibited this api from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @api.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :api_key, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :api_key, :class => 'form-control' %>
    </div>
    <%= error_span(@api[:api_key]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            apis_path, :class => 'btn btn-default' %>

<% end %>

app/views/apis/edit.html.erb
<%- model_class = Api -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/apis/index.html.erb
<%- model_class = Api -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:api_key) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @apis.each do |api| %>
      <tr>
        <td><%= link_to api.id, api_path(api) %></td>
        <td><%= api.api_key %></td>
        <td><%=l api.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_api_path(api), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      api_path(api),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_api_path,
            :class => 'btn btn-primary' %>

app/views/apis/new.html.erb
<%- model_class = Api -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/apis/show.html.erb
<%- model_class = Api -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:api_key) %>:</strong></dt>
  <dd><%= @api.api_key %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              apis_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_api_path(@api), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              api_path(@api),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>